adding docker compose as a sanity

diff --git a/Jenkins/CD/jenkinsfile b/Jenkins/CD/jenkinsfile
--- a/Jenkins/CD/jenkinsfile
+++ b/Jenkins/CD/jenkinsfile
@@ -129,63 +129,39 @@ pipeline {
                 }
             }
         }
-        // stage("apt update upgrade") {
-        //     steps {
-        //         sh "sudo apt update && sudo apt upgrade -y"
-        //     }
-        // }
-        // stage("terraform installing") {
-        //     steps {
-        //         sh """
-        //             # Ensure jq is installed to parse JSON
-        //             if ! dpkg -l | grep -q jq; then
-        //                 sudo apt install -y jq
-        //             fi
+        stage("apt update upgrade") {
+            steps {
+                sh "sudo apt update && sudo apt upgrade -y"
+            }
+        }
+        stage("terraform installing") {
+            steps {
+                sh """
+                    if ! command -v terraform &> /dev/null; then
+                        sudo apt install -y jq
+                        sudo apt install -y wget
+                        sudo apt install -y unzip
+                        latest_version=\$(wget -qO- https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].version' | sort -V | tail -n 1)
+                        wget https://releases.hashicorp.com/terraform/\${latest_version}/terraform_\${latest_version}_linux_amd64.zip     
+                        unzip terraform_\${latest_version}_linux_amd64.zip
+                        sudo mv terraform /usr/local/bin/
+                        rm terraform_\${latest_version}_linux_amd64.zip  # Clean up zip file
+                    else
+                        echo "Terraform is already installed, skipping installation."
+                    fi
 
-        //             # Check if wget is installed, install if missing
-        //             if ! dpkg -l | grep -q wget; then
-        //                 sudo apt install -y wget
-        //             fi
-                                        
-        //             # Check if unzip is installed, install if missing
-        //             if ! dpkg -l | grep -q unzip; then
-        //                 sudo apt install -y unzip
-        //             fi
-
-        //             # Check if Terraform is already installed
-        //             if ! command -v terraform &> /dev/null; then
-        //                 echo "Terraform not found, installing..."
-
-        //                 # Get the latest Terraform version
-        //                 latest_version=\$(wget -qO- https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].version' | sort -V | tail -n 1)
-        //                 echo "Latest Terraform version: \$latest_version"  # Log the version being used
-
-        //                 # Attempt to download the latest Terraform version
-        //                 #wget https://releases.hashicorp.com/terraform/\${latest_version}/terraform_\${latest_version}_linux_amd64.zip
-                        
-        //                 # Unzip and move terraform binary to /usr/local/bin
-        //                 #unzip terraform_\${latest_version}_linux_amd64.zip
-        //                 #sudo mv terraform /usr/local/bin/
-        //                 #rm terraform_\${latest_version}_linux_amd64.zip  # Clean up zip file
-        //             else
-        //                 echo "Terraform is already installed, skipping installation."
-        //             fi
-
-        //             # Verify Terraform installation
-        //             terraform --version
-        //         """
-        //     }
-        // }
+                    # Verify Terraform installation
+                    terraform --version
+                """
+            }
+        }
 
         stage("k8s update") {
             steps {
                 echo "====++++executing A++++===="
                 sh "date"
                 sh "pwd"
-                sshagent(ubuntu ['c80b552a-e358-4c71-87c8-89b328937b08']) {
-                    sh "pwd"
-                    sh "whoami"
-                    sh "date"
+                sshCommand([host: '3.70.39.129', username: 'ubuntu', identityFile: '/var/jenkins_home/workspace/CD-social-media-scraper/Jenkins/CD/testing.pem'], command: 'your-command')
                 }
                 // script {
                 //     sshagent(credentials : ['jenkins-pem']) {
@@ -194,7 +170,6 @@ pipeline {
                 //         sh "echo pwd"
                 //     }
                 //  }
-             }
-         }     
+        }    
     }
 }
